### ISSUE TITLE
Zeiten in Highscore nicht an Spalte ausgerichtet

### ISSUE THREAD

**Issue by bscx** [dasfabs/Kingdom4#114]
Mindestens der Spalte für die Spielzeit fehlt noch die Ausrichtung.
Vorschlag: rechtsbündig.

**Comment by dasfabs** [comment]
Textalign steht auf right. Ich liebe java

**Comment by bscx** [comment]
Sah gerade gut aus; du hast es schon behoben?

**Comment by bscx** [comment]
Sieht gut aus, vielen Dank!
