### ISSUE TITLE
Pixelzugabe nach Introscreen

### ISSUE THREAD

**Issue by bscx** [dasfabs/Kingdom4#119]
Ich schlage vor, nach dem Introscreen nur einen Pixel zuzugeben.
Ich stelle gerne einen PR dafür.
@masanfi @dasfabs

**Comment by dasfabs** [comment]
Dann sieht es bei mir scheiße aus :/

**Comment by bscx** [comment]
Okay, dann müssen wir rausfinden, wie es dazu kommt und das Problem beheben. Da scheint es ja unterschiedlich große Hintergründe/Sceneries zu geben.

**Comment by dasfabs** [comment]
die allerdings von osx und windows unterschiedlich interpretiert werden

**Comment by bscx** [comment]
Ich gehe davon aus, dass genau gleich große Hintergründe auch genau gleich interpretiert würden.

**Comment by masanfi** [comment]
Ich habe den Hintergrund damals nach der Vorgabe von Fabis Screenshot gemacht. Ist der eventuell zu groß?

**Comment by bscx** [comment]
Mein Gedanke war, dass der Hintergrund vielleicht 10 Pixel auf jeder Seite zu klein ist, aber ich weiß nicht, was der Hintergrund dieser Zeilen ist:

        int paneWidth = gameEngine.getPaneWidth()-10;
    	int paneHeight = gameEngine.getPaneHeight()-10;

in Scenery.java

**Comment by dasfabs** [comment]
die beiden Zeilen sorgen dafür, dass das Fenster nicht springt, zumindest bei mir

**Comment by bscx** [comment]
#126 fixt das hoffentlich

**Comment by bscx** [comment]
@dasfabs Wenn es bei dir gut aussieht, schließe hier bitte. Ansonsten dein Fix ins else via PR und anschließend close.

**Comment by dasfabs** [comment]
Perfekt vielen Dank für eure Mühen
