### ISSUE TITLE
Hinweistext beim Einsammeln von Trophies

### ISSUE THREAD

**Issue by bscx** [dasfabs/Kingdom4#121]
Wenn eine Tropy eingesammelt wird, sollte ein Hinweistext erscheinen.

**Comment by bscx** [comment]
#130 should do the trick.
@masanfi @dasfabs Happy testing

**Comment by masanfi** [comment]
Läuft! Super gemacht.

Hab das Layout noch angepasst und aus den Pokalen ordnungsgemäß Orden gemacht. Niemand hat Pokale gezeichnet ;)

**Comment by dasfabs** [comment]
Sehr geil vielen Dank
