### ISSUE TITLE
Zufallsgenerator für die Konversation mit dem Weisen

### ISSUE THREAD

**Issue by dasfabs** [dasfabs/Kingdom4#127]

**Comment by dasfabs** [comment]
Also die Zufall wird jetzt wenig beeinflusst. Da ihr ja genau Fehlerbeschreibungen haben wollt hier eine warum RandomInt nicht so erfolgreich war wie gedacht:
An der Stelle wo die zufallszahl generiert wurde wurde der Quelltext tausende Male aufgerufen durch die berührung des Triggers, dies habe ich die Ändern der Reihenfolge der Bedingung geändert. Zudem merkt er sich gesprochenes dass es sich nicht wiederholt bis er alles einmal gesagt hat.

Viel Spaß beim Testen @masanfi @bscx

**Comment by bscx** [comment]
Eroh fragt weisen Mann nach Prinzessin, ohne mit Derni Ydal darüber gesprochen zu haben.

**Comment by masanfi** [comment]
Ist behoben, er weißt jetzt auf Derni Ydal hin.

**Comment by bscx** [comment]
Eroh antwortet, dass er eine Prinzessin retten möchte, obwohl er von ihr noch nichts weiß.

Character states:
-----------------
Lady: 0
Knight: 0
Blacksmith: 0
Fisherman: 0
Wise man: 1
Knight2: 0
 
Inventory states:
-----------------
Rabbit: false
Sword: false
Key: false
Fish: false

**Comment by masanfi** [comment]
fixed
