### ISSUE TITLE
Fisher redet nicht

### ISSUE THREAD

**Issue by dasfabs** [dasfabs/Kingdom4#141]
Character states:
-----------------
Lady: 1
Knight: 2
Blacksmith: 2
Fisherman: 0
Wise man: 0
Knight2: 0
 
Inventory states:
-----------------
Rabbit: false
Sword: true
Key: false
Fish: false

**Comment by bscx** [comment]
@dasfabs Schaust du nochmal?

**Comment by dasfabs** [comment]
Funzt super, Danke
