### ISSUE TITLE
Check conversation logic once again

### ISSUE THREAD

**Issue by bscx** [dasfabs/Kingdom4#148]
Pending issue in case someone encounters issues while having a conversation with a NPC.
Please make sure to paste the states by pressing "S".

**Comment by bscx** [comment]
#147 is fixed

**Comment by bscx** [comment]
#150

**Comment by bscx** [comment]
#151 fixt Folgendes:
Wenn man zum weisen Mann läuft und nie mit der Prinzessin gesprochen hat, sollte Eroh ab und an "Was gibt's Neues?" fragen. Dafür wird der State vom weisen Mann auf 0 gesetzt. Was aber passiert, ist Folgendes: Durch das Setzen auf 0 fällt das Gespräch wieder in den "Wo ist die Prinzessin?"-Ast zurück. Es gibt nur einen zuverlässigen Weg in "Was gibt's Neues?" zu fallen: Mehrmals mit der Lady sprechen und erst dann zum weisen Mann gehen. Daher haben wir den Code gelöscht.

**Comment by dasfabs** [comment]
Der knight reagiert auch nicht auf die Aussage "schau mal ein Ufo"

**Comment by masanfi** [comment]
Kommt die letzte Speechbubble nicht? #WorstErrorDepreciation

**Comment by bscx** [comment]
Alle Sprechblasen erscheinen, aber der Ritter geht inhaltlich nicht auf den Hinweis mit dem UFO ein.

**Comment by masanfi** [comment]
Hier gibt es keine UFOs, bitte gehen sie weiter.
