### ISSUE TITLE
Fluss fließt nicht

### ISSUE THREAD

**Issue by dasfabs** [dasfabs/Kingdom4#152]
das ist doch bestimmt noch umsetzbar :P

**Comment by bscx** [comment]
Mir würde auch eine Entenmutter mit Küken gefallen, die ab und an vorbeischwimmen. Gerne mit Quak-Geräuschen.

**Comment by masanfi** [comment]
Was war heute morgen in euren Laugenbrötchen? Oder hatte Boris nicht ausreichend gelüftet?

**Comment by bscx** [comment]
Also, noch heute?

**Comment by masanfi** [comment]
Das einzige, was hier fließt, sind gleich deine Tränen!

**Comment by bscx** [comment]
Wenn ich Martin richtig verstanden habe, dann meinte er was von Schafen, die am Wegesrand grasen und künstlicher Intelligenz.

**Comment by masanfi** [comment]
Ticket wegen Dummheit geschlossen.

**Comment by bscx** [comment]
Versehentlich geschlossen.

**Comment by masanfi** [comment]
so sad

**Comment by bscx** [comment]
:(
