### ISSUE TITLE
Hero redet nicht mit Wiseman

### ISSUE THREAD

**Issue by dasfabs** [dasfabs/Kingdom4#157]
Character states:
-----------------
Lady: 2
Knight: 0
Blacksmith: 0
Fisherman: 0
Wise man: 1
Knight2: 0
 
Inventory states:
-----------------
Rabbit: false
Sword: false
Key: false
Fish: false

**Comment by dasfabs** [comment]
fixed, ready to test

**Comment by masanfi** [comment]
fixed
