### ISSUE TITLE
Konversation mit NPCs

### ISSUE THREAD

**Issue by bscx** [dasfabs/Kingdom4#31]
Der Held soll die Möglichkeit haben, mit einem NPC kommunizieren zu können.

**Comment by masanfi** [comment]
Wir müssen noch entscheiden, ob wir die Kommunikation grundsätzlich als Sprechblasen anzeigen wollen. Oder ob diese ins HUD wandern soll.

Sollte es bei Sprechblasen bleiben, müssen wir noch eine Abfrage bauen, wo der Spieler im Verhältnis zum NPC steht. Denn die Sprechblase sollte den Helden nicht überdecken, bzw. er sollte nicht drauf stehen.

**Comment by bscx** [comment]
Ist erstmal erledigt.
