### ISSUE TITLE
Trophy System

### ISSUE THREAD

**Issue by dasfabs** [dasfabs/Kingdom4#32]
Wie bei der Playstation

**Comment by masanfi** [comment]
Mögliche Trophys:
Treehugger - Du bist gegen 20 Bäume gelaufen. 
Trampel - Du bist über 20 Blumenbeete gelaufen.
Influencer - Du hast 15 mal einen NPC angesprochen.
Verwirrt - Du hast drei mal die Brücke betreten.
Perfektionist - Du bist gegen keinen einzigen Baum gelaufen.

**Comment by dasfabs** [comment]
Steinbeißer

**Comment by bscx** [comment]
Während der Gespräche läuft der Trophycounter für NPCs hoch. @dasfabs Muss ich das in meiner Conversations-Klasse verhindern oder machst du das über eine Identifizierung der NPCs?

**Comment by bscx** [comment]
Richtig tolle Arbeit, @dasfabs 
Die Fanfare bei eingesammelter Trophy wird nur bei der ersten Trophy abgespielt (OS X)

**Comment by bscx** [comment]
Wow, @dasfabs und @masanfi
