### ISSUE TITLE
HUD ausbauen

### ISSUE THREAD

**Issue by bscx** [dasfabs/Kingdom4#36]
Ein HUD wurde vorbereitet, es fehlt eine Hintergrundgrafik und die genaue Definition, was das HUD anzeigen soll.

**Comment by masanfi** [comment]
Hab ne erste Idee für das HUD. Baue ich dann nach dem Wochenende mal ein.

In der HUD Grafik sollten wir drei Felder definieren, in denen wir die gesammelten Gegenstände anzeigen. 

Wollen wir den Spieltitel immer im HUD stehen haben?

**Comment by dasfabs** [comment]
Ja machen wir so

**Comment by bscx** [comment]
@dasfabs Trophies bitte mit einem "Daumen" breit Abstand und etwas kleiner. Dazu noch bitte einen Rahmen um die eingesammelten Items. (@masanfi brauchen wir da Hilfe von dir?)

**Comment by dasfabs** [comment]
Folgende Befehle für den HUD sind möglich

gameEngine.getPickedUpItems();
--> Rückgae ist ein ARRAY mit 3 Feldern analog zu der Ansicht in der HUD, er kann folgende Buchstaben enthalten: F (fish),S (sword),R(rabbit),K (key)

Elemente abgeben kann man mit:
gameEngine.findRemovePickedUpItem(String name);
--> name ist gleich der Buchstaben der der 4 Elemente

Elemente aufnehmen kann man mit:
gameEngine.setPickedUpItem(Image image, String name);
--> image ist das Bild, alle bekannt in der gameEngine fish,sword,key,rabbit
--> name der jeweilige Buchstabe des Bildes wie oben

**Comment by bscx** [comment]
Großartige Arbeit, @masanfi und @dasfabs
