### ISSUE TITLE
Grafiken für NPCs

### ISSUE THREAD

**Issue by bscx** [dasfabs/Kingdom4#37]
Diverse NPCs haben noch keine Grafiken.

**Comment by masanfi** [comment]
Fehlen euch noch NPCs? Sonst kann der issue zu.

**Comment by bscx** [comment]
Vielleicht eine einzige noch, die ganz am Anfang in der Nähe des Held steht. Damit wird zum einen klar, "wie" man mit einem NPC spricht (indem man dagegen läuft) und zum anderen kann dieser NPC die Motivation des Spiels klarmachen ("auf die andere Seite des Flusses zu gelangen"). Aber nur so eine Idee und auch nur, wenn es dir nicht mehr als 10 Minuten Arbeit macht.

**Comment by masanfi** [comment]
Erledigt.
