### ISSUE TITLE
Startmenü / Endscene

### ISSUE THREAD

**Issue by dasfabs** [dasfabs/Kingdom4#40]

**Comment by dasfabs** [comment]
@dasfabs

**Comment by dasfabs** [comment]
Willkommensbildschirm mit Startbutton

Ende mit Highscore

**Comment by masanfi** [comment]
Da wir was speichern sollen, sollte dort auch ein "Spiel laden" oder "Spiel fortführen" vorhanden sein.

**Comment by dasfabs** [comment]
ne aber Playernamen eingeben für die Highscore

**Comment by masanfi** [comment]
Startscreen steht soweit.
Endscreen muss noch schöner werden!

**Comment by dasfabs** [comment]
CSS table design ohne Überschrift

**Comment by masanfi** [comment]
Outroscreen hinzugefügt. Closed?

**Comment by bscx** [comment]
Danke für eure erstklassige Arbeit.
