### ISSUE TITLE
Hintergrund Musik und Gespäche

### ISSUE THREAD

**Issue by dasfabs** [dasfabs/Kingdom4#45]

**Comment by masanfi** [comment]
Umsetzung voraussichtlich Januar.

**Comment by masanfi** [comment]
Code sollte vorbereitet sein auf:
Musik (Hintergrund)
Sprachfiles (Wenn NPC spricht)
Laufgeräusche (Wenn Spieler sich bewegt)
Aktionsgeräusche (Wenn Item eingesammelt wird)
Fanfare (Bei Anzeige des Highscore)

**Comment by masanfi** [comment]
Menü-Musik, Hintergrundmusik und Fanfare laufen. Der Rest wird aus Kapazitätsgründen nicht kommen.
