### ISSUE TITLE
Animation läuft bei diagonaler Bewegung zu schnell

### ISSUE THREAD

**Issue by bscx** [dasfabs/Kingdom4#50]
Die Animation der Laufbewegung läuft bei einer beliebigen diagonalen Bewegung zu schnell ab.

**Comment by dasfabs** [comment]
wurde gefixt, jetzt darf er allerdings nur noch in eine Richtung und hält bei zwei Richtungen einfach an

**Comment by dasfabs** [comment]
Weiterlaufen, zusätzliche Richtungen werden nicht akzeptiert

**Comment by dasfabs** [comment]
Es wir der aktuelle Anschlag angenommen mehr nicht
