### ISSUE TITLE
Feinschliff für Konversationen

### ISSUE THREAD

**Issue by bscx** [dasfabs/Kingdom4#98]
Noch einmal die Konversationen durchgehen und die States auf Logikfehler überprüfen.

**Comment by dasfabs** [comment]
Habe es heute nochmal gespielt, mir ist erstmal kein Fehler aufgefallen, würde allerdings die Abgabe des Schlüssels und das bekommen des Fisches etwas verzögern damit das Bild nicht vor dem Text erscheint. Ansonsten super Arbeit. Lasse heute nochmal meine Kollegen spielen, vielleicht finden die noch was

**Comment by bscx** [comment]
Der Fischer sollte nach der ersten Ansprache den State wechseln, da die Konversation sehr lang ist und er bei erneuter Begegnung einfach alles wiederholt.

**Comment by masanfi** [comment]
Mach ich, wenn der PR angenommen ist.

**Comment by masanfi** [comment]
Letzter Aufruf. Gibt es noch Probleme oder Fehler?

**Comment by bscx** [comment]
Für mich ist alles schick.
