### ISSUE TITLE
Highscores werden nicht zuverlässig angezeigt

### ISSUE THREAD

**Issue by bscx** [dasfabs/Kingdom4#99]
Entweder werden die Highscores nicht zuverlässig übertragen oder die Anzeige wird unzuverlässig gefiltert. (Eventuell wird nach Anzahl der Trophies gefiltert?)

**Comment by bscx** [comment]
Sieht gut aus.
Was meinst du, @masanfi ?

**Comment by masanfi** [comment]
Top, ich mach noch nen neuen background-screen und dann sollte es passen!

**Comment by bscx** [comment]
Sieht perfekt aus.
